name: build miniclash

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Manual Trigger'
        required: false
        default: 'Build'
        
env:
 TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3  
       # permissions:
       # contents: write

      - name: Set variables
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo apt-get -y  install jq 
          echo  "VERSION=$(curl -sL https://api.github.com/repos/Dreamacro/clash/releases/latest | jq -r ".tag_name")" >> $GITHUB_ENV
   
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19
          
      - name: Install dependencies
        run: go get -u
        
      - name: Build
        run: |         
          CGO_ENABLED=0 GOOS=windows GOARCH=amd64 go build -ldflags "-s -w -H=windowsgui" -o MiniClash.exe 

      - name: Upload binaries to release
        uses: softprops/action-gh-release@v1
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          body: update to ${{ env.VERSION }}
          files: MiniClash.exe
          name: ${{ env.VERSION }}
          tag_name: ${{ env.VERSION }}
          token: ${{ secrets.PRIVATE_TOKEN }}
        env:
          GITHUB_REPOSITORY: gfw-list/MiniClash
          
      - name: Upload to webdav 
        uses: bxb100/action-upload-webdav@v1
        with:
          webdav_address: ${{secrets.address}}
          webdav_username: ${{secrets.username}}
          webdav_password: ${{secrets.password}}
          webdav_upload_path: "/Windows"
          files: "MiniClash.exe"
          
      - name: Clean up
        uses: igorjs/gh-actions-clean-workflow@v3
        with:
          token: ${{ secrets.PRIVATE_TOKEN }}
          owner: ${{ github.repository_owner }}
          repo: ${{ github.event.repository.name }}
          days_old: 3
